// Array de colonias
const colonias = [
    'Otra',
    "Barrio Guadalupe",
    "Barrio San Agustín",
    "Barrio San Antonio",
    "Barrio San Francisco",
    "Barrio San Isidro",
    "Barrio San José",
    "Barrio San Mateo",
    "Barrio Santa Cruz",
    "Barrio Santa Cruz Norte",
    "Barrio Tequicorral",
    "Colonia 10 de Abril",
    "Colonia 10 de Junio",
    "Colonia 12 de Septiembre",
    "Colonia 14 de Febrero",
    "Colonia 16 de Septiembre",
    "Colonia 1ro de Marzo",
    "Colonia 1ro de Mayo",
    "Colonia 21 de Marzo",
    "Colonia 21 de Septiembre",
    "Colonia 24 de Febrero",
    "Colonia 4 de Marzo",
    "Colonia 6 de Julio",
    "Colonia Acahuizotla",
    "Colonia Agua Potable",
    "Colonia Agua Zarca",
    "Colonia Ahuiyuco",
    "Colonia Alianza Popular",
    "Colonia Amelitos",
    "Colonia América",
    "Colonia Amolonga",
    "Colonia Ampliación Lázaro Cárdenas",
    "Colonia Ampliación Leyes de Reforma",
    "Colonia Ampliación Primer Congreso de Anáhuac",
    "Colonia Anáhuac",
    "Colonia Ángel Aguirre Rivero",
    "Colonia Antonio I. Delgado",
    "Colonia Apantzingo",
    "Colonia Asociación Civil",
    "Colonia Atlitenco de Altamira",
    "Colonia Atlitenco Oriente",
    "Colonia Azteca",
    "Colonia Balcones de Tepango",
    "Colonia Barranca Pezuapa",
    "Colonia Barranco de Tequimil",
    "Colonia Bella Vista",
    "Colonia Benito Juárez",
    "Colonia Brisas del Sur",
    "Colonia Buenos Aires",
    "Colonia Bugambilias",
    "Colonia Burócratas",
    "Colonia Caminos",
    "Colonia Campestre Santa Rosa",
    "Colonia Chilpancingo de los Bravos Centro",
    "Colonia Cipatli",
    "Colonia Ciudad de los Servicios",
    "Colonia CNOP Secc C",
    "Colonia CNOP Sección A",
    "Colonia CNOP Sección B",
    "Colonia Colinas del Sur",
    "Colonia Cooperativa de Vivienda",
    "Colonia Corregidora",
    "Colonia Cuauhtémoc",
    "Colonia Cuauhtémoc Norte",
    "Colonia Cuauhtémoc Sur",
    "Colonia Cuitlahuac",
    "Colonia Cumbres del Poniente",
    "Colonia Del PRI",
    "Colonia Del Valle",
    "Colonia Diana Laura Riojas de Colosio",
    "Colonia Dr. Catalán",
    "Colonia Eduardo Neri",
    "Colonia El Calvario",
    "Colonia El Encanto",
    "Colonia El Huajal",
    "Colonia El Mirador",
    "Colonia El Ocotito Centro",
    "Colonia El Polvorín",
    "Colonia El Porvenir",
    "Colonia El Potrerito",
    "Colonia El Salado",
    "Colonia El Tomatal",
    "Colonia Electricistas",
    "Colonia Elías Naime Nemer",
    "Colonia Emiliano Zapata",
    "Colonia Ex-Hacienda San Nicolás",
    "Colonia Flor de Nochebuena",
    "Colonia Francisco Figueroa Mata",
    "Colonia Francisco Javier Mina",
    "Colonia Francisco Ruiz Massieu Sur",
    "Colonia Francisco Villa",
    "Colonia Guadalupe",
    "Colonia Guerrero",
    "Colonia Guerrero 200",
    "Colonia Haciendita",
    "Colonia Haciendita Aeropuerto",
    "Colonia Haciendita II",
    "Colonia Heberto Castillo",
    "Colonia Hermanos Neri",
    "Colonia Hermenegildo Galeana",
    "Colonia Héroes de Guerrero",
    "Colonia Huacapita",
    "Colonia Huaxcorral",
    "Colonia Ignacio Manuel Altamirano",
    "Colonia INDECO (Unidad Guerrerense)",
    "Colonia Independencia",
    "Colonia Inviso",
    "Colonia Ixquiapan",
    "Colonia Jacarandas",
    "Colonia Jardín los Pinos",
    "Colonia Jardines del Sur",
    "Colonia José Francisco Ruiz Massieu",
    "Colonia José López Portillo",
    "Colonia José María Izazaga",
    "Colonia José María Pino Suárez",
    "Colonia Juan N Alvarez",
    "Colonia Juana Arcos de Moreno",
    "Colonia Juquila",
    "Colonia Juquila Oriente",
    "Colonia La Cañada",
    "Colonia La Ciénega",
    "Colonia La Cima",
    "Colonia La Cinca",
    "Colonia La Esperanza",
    "Colonia La Floresta",
    "Colonia La Florida",
    "Colonia La Herradura",
    "Colonia La Ladera",
    "Colonia La Pradera",
    "Colonia La Sierrita",
    "Colonia La Trinchera",
    "Colonia Las Américas",
    "Colonia Las Palmas",
    "Colonia Las Terrazas",
    "Colonia Las Torres",
    "Colonia Lázaro Cárdenas",
    "Colonia Libertad",
    "Colonia Linda Vista",
    "Colonia Loma Alegre",
    "Colonia Loma Bonita",
    "Colonia Lomas de Guadalupe",
    "Colonia Lomas de Ocotepec",
    "Colonia Lomas de San Antonio",
    "Colonia Lomas de San Mateo",
    "Colonia Lomas de Xocomulco",
    "Colonia Lomas del Bosque",
    "Colonia Lomas del Poniente",
    "Colonia Lomas del Porvenir",
    "Colonia Lomas Verdes",
    "Colonia Los Ángeles",
    "Colonia Los Cedros",
    "Colonia Los Gobernadores",
    "Colonia Los Lirios",
    "Colonia Los Manantiales",
    "Colonia Los Puentes",
    "Colonia Los Romeros",
    "Colonia Los Sauces",
    "Colonia Lucía Alcocer de Figueroa",
    "Colonia Luis Donaldo Colosio",
    "Colonia Magisterial",
    "Colonia Margarita Viguri",
    "Colonia María de la O",
    "Colonia María Dolores",
    "Colonia Martires Antorchistas",
    "Colonia México",
    "Colonia Miguel Hidalgo",
    "Colonia Militar",
    "Colonia Milpizaco",
    "Colonia Misiones de Guadalupe",
    "Colonia Moctezuma",
    "Colonia Morelos",
    "Colonia Movimiento Territorial",
    "Colonia Nicolás Bravo",
    "Colonia Niños Héroes",
    "Colonia Norberto Flores Baños",
    "Colonia Nueva Imagen",
    "Colonia Nuevo Horizonte",
    "Colonia Nuevo Milenio",
    "Colonia Obrera",
    "Colonia Ocozoapa",
    "Colonia Omiltemi",
    "Colonia OPCG",
    "Colonia Palo María",
    "Colonia Paludismo",
    "Colonia Panorámica",
    "Colonia Paraíso del Sol",
    "Colonia Paraíso Siglo XXI",
    "Colonia Pensadores",
    "Colonia Periodistas",
    "Colonia Plan de Ayala",
    "Colonia Plutarco Elías Calles",
    "Colonia PPS",
    "Colonia PRD",
    "Colonia Primer Congreso de Anáhuac",
    "Colonia Progreso",
    "Colonia PRT",
    "Colonia Reforma",
    "Colonia Reforma Universitaria",
    "Colonia Renacimiento",
    "Colonia Renovación",
    "Colonia Revolución",
    "Colonia Ricardo Flores Magón",
    "Colonia Rodolfo Neri Vela",
    "Colonia Rosario Ibarra",
    "Colonia Rubén Mora",
    "Colonia Ruffo Figueroa",
    "Colonia Salubridad",
    "Colonia San Ángel",
    "Colonia San Isidro",
    "Colonia San José",
    "Colonia San José Chuchululuya",
    "Colonia San Juan",
    "Colonia San Lucas",
    "Colonia San Miguelito",
    "Colonia San Pedro",
    "Colonia San Rafael Norte",
    "Colonia San Rafael Oriente",
    "Colonia Santa Fe",
    "Colonia Santa Rosa",
    "Colonia SARH",
    "Colonia Satélite",
    "Colonia Sección Septima",
    "Colonia Servidor Agrario",
    "Colonia Servidor Publico",
    "Colonia Simapa",
    "Colonia SNTE",
    "Colonia STTAISUAG",
    "Colonia Tata Gildo",
    "Colonia Telumbre",
    "Colonia Temixco",
    "Colonia Temixco II",
    "Colonia Tepolzingo",
    "Colonia Tepozoteapa",
    "Colonia Texcalco",
    "Colonia Tierra Larga",
    "Colonia Tierra y Libertad",
    "Colonia Tierras Prietas",
    "Colonia Timotlán",
    "Colonia Tlacaellel",
    "Colonia Tribuna Nacional",
    "Colonia Unidad Deportiva",
    "Colonia Unidad Magisterial Los Pinos",
    "Colonia Universal",
    "Colonia Universidad",
    "Colonia Universitarios Unidos Por Guerrero",
    "Colonia Valle Dorado",
    "Colonia Valle Esmeralda",
    "Colonia Valle Verde Norte",
    "Colonia Vicente Guerrero",
    "Colonia Vicente Lombardo Toledano",
    "Colonia Villa de las Flores",
    "Colonia Villa del Roble",
    "Colonia Villa Lucerna",
    "Colonia Villa Moderna",
    "Colonia Villa Victoria",
    "Colonia Villas Aparicio",
    "Colonia Villas Caminos del Sur",
    "Colonia Villas de Leyva",
    "Colonia Villas del Parador",
    "Colonia Villas del Sol",
    "Colonia Villas Tlalmeca",
    "Colonia Vista Alegre",
    "Colonia Vista Hermosa",
    "Colonia Vista Hermosa",
    "Ejido San Vicente",
    "Equipamiento CERESO Chilpancingo, Gro.",
    "Fraccionamiento 20 de Noviembre",
    "Fraccionamiento Azteca",
    "Fraccionamiento Bosques de las Lomas",
    "Fraccionamiento Calli Calmecac",
    "Fraccionamiento CBTIS",
    "Fraccionamiento Country",
    "Fraccionamiento Don Ely",
    "Fraccionamiento El Amate",
    "Fraccionamiento Eucalipto",
    "Fraccionamiento Huicacalli",
    "Fraccionamiento Huitzicatzin",
    "Fraccionamiento India Bonita",
    "Fraccionamiento Insurgentes de Guerrero",
    "Fraccionamiento Jacarandas",
    "Fraccionamiento Jardines de Zinnia",
    "Fraccionamiento José Vasconcelos",
    "Fraccionamiento Las Águilas",
    "Fraccionamiento Las Joyas",
    "Fraccionamiento Las Margaritas",
    "Fraccionamiento Linaloe",
    "Fraccionamiento Los Alarcón",
    "Fraccionamiento Los Garzón",
    "Fraccionamiento Los Girasoles",
    "Fraccionamiento Melendez",
    "Fraccionamiento Moisés Villegas",
    "Fraccionamiento Olinalá",
    "Fraccionamiento Ombu",
    "Fraccionamiento Paseo del Sur",
    "Fraccionamiento Real del Valle",
    "Fraccionamiento Reforma",
    "Fraccionamiento Residencial Bugambilias",
    "Fraccionamiento Residencial Juristas",
    "Fraccionamiento Rinconada de Ocotepec",
    "Fraccionamiento Río Azul",
    "Fraccionamiento Riviera",
    "Fraccionamiento Sedue",
    "Fraccionamiento SUSPEG Guerrero Cumple",
    "Fraccionamiento Valle Verde",
    "Fraccionamiento Victoria",
    "Fraccionamiento Villa Esperanza",
    "Fraccionamiento Villas de Ocotepec",
    "Fraccionamiento Villas Laurel",
    "Fraccionamiento Villas Magisteriales",
    "Fraccionamiento Villas San Rafael",
    "Fraccionamiento Villas Silvestre",
    "Fraccionamiento Villas Vicente Guerrero",
    "Pueblo Amojileca",
    "Pueblo Buena Vista de la Salud",
    "Pueblo Cajelitos",
    "Pueblo Cuacoyulillo",
    "Pueblo El Fresno",
    "Pueblo Gral. Heliodoro Castillo",
    "Pueblo Inscuinatoyac",
    "Pueblo Jaleaca de Catalán",
    "Pueblo Julián Blanco (Dos Caminos)",
    "Pueblo Mazatlán",
    "Pueblo Mohoneras",
    "Pueblo Palo Blanco",
    "Pueblo San Cristóbal",
    "Pueblo Santa Bárbara",
    "Pueblo Tepechicotlán",
    "Pueblo Tlahuizapa",
    "Pueblo Zoyatepec",
    "Ranchería Agua Hernández",
    "Ranchería Azinyahualco (Cañada de Azingehualco)",
    "Ranchería Carrizal de Pinzón",
    "Ranchería Chautipan",
    "Ranchería Coapango",
    "Ranchería El Ciruelar",
    "Ranchería Huiteco",
    "Ranchería La Esperanza",
    "Ranchería La Haciendita",
    "Ranchería Río Verde",
    "Ranchería San Miguel",
    "Ranchería Santa Rita y Tecalco",
    "Unidad habitacional INFONAVIT",
    "Zona industrial Zona Industrial",
    "Zona militar 35/a Z. M. Chilpancingo, Gro."
    ];

    export default colonias;